# query ProjectOwner($id: String!) {
#   projectOwner: projectOwner(id: $id) {
#     name
#   }
# }

query Project($id: String!) {
  project: project(id: $id) {
    name
  }
}

# mutation Login($login: String!, $password: String!, $remember: Boolean!) {
#   login: login(login: $login, password: $password, remember: $remember) {
#     login
#   }
# }
