query ProjectOwner($id: String!) {
  projectOwner: projectOwner(id: $id) {
    name
  }
}

query Viewer {
  viewer {
    login
  }
}

mutation Register($email: String!, $login: String!, $password: String!) {
  register(email: $email, login: $login, password: $password) {
    userId
    refreshToken
    accessToken
  }
}

mutation Login($login: String!, $password: String!, $remember: Boolean!) {
  login(login: $login, password: $password, remember: $remember) {
    userId
    refreshToken
    accessToken
  }
}

# query Viewer {
#   viewer {
#     id
#     name
#     profile {
#       publicEmail
#       description
#     }
#   }
# }
